uitext
getUiText: aKey language: aLanguage
	| dictKey |
	dictKey := self uiTextKeyFor: aKey language: aLanguage.

	^uiTexts at: dictKey ifAbsent: [
"failsafe		aKey isTranslationKey
			ifFalse: [
				^VIAHelper pillarFromPillarString: aKey]
			ifTrue: ["
				"Default in allen Sprachen installieren"
"				self languages do: [:each |
					self ensureUiText: aKey language: each
				]."

				"If not a key, then its probably a normal text"
				aKey isTranslationKey ifFalse: [ ^ VIAHelper pillarFromPillarString: aKey ].

				"Nur in 1 Sprache default setzen, da wir auch für Backend Texte in English haben"
				self ensureUiText: aKey language: aLanguage.
			
				^self uiTextAt: dictKey]