sample-data
sampleClozePillar
	^'!Il grande test di Lückentext
Chi e ${note:questo|D:Dieser Typ|F:Ce lui la}$?
+Silvio Berlu_sconi_>http://upload.wikimedia.org/wikipedia/commons/thumb/c/c1/Berlusconi-2010-1.jpg/220px-Berlusconi-2010-1.jpg+
	
#""In treno"": Potrebbe chiudere il finestrino, _per favore_? – Certo, subito.
#""Dal medico"": Posso entrare? – _Prego_, può accomodarsi.

Tabelle:
||""Deutsch""||""Italienisch""||Bemerkungen
| Bitte als Frage | _3_ | ''''Hinweis: blabla blabla''''
| Bitte als Antwort | _4_ | 

Etwas ""fettes _Brot_""

Etwas ''''kursiv''''

Etwas --durchgestrichen--

Etwas __unterstrichen__

Etwas ==Schreibmaschinenschrift==

Etwas @@subscript@@

Etwas ^^hochgest_ellt_^^
'