as yet unclassified
updateRootStandardJsUiLibs: anHtmlRoot

	"Mouse/Touch events unifier for dragging, ..."
	"TODO: Maybe only as feature request in a module exerciser?"
	"Previous used version: 1.10.3"
	anHtmlRoot javascript defer; url: 'https://cdn.jsdelivr.net/npm/interactjs@1.10.11/dist/interact.min.js'.

	"List drag/drop sorting library"
	"TODO: Maybe only as feature request in a module exerciser?"
	anHtmlRoot javascript defer; url: 'https://cdn.jsdelivr.net/npm/sortablejs@latest/Sortable.min.js'.

	"Textareas autosizing"
	anHtmlRoot javascript defer; url: '/js/jquery.autosize.js'.

