as yet unclassified
updateRootDefaultUi: anHtmlRoot

	anHtmlRoot javascript defer; url: '/lib/uikit-3/js/uikit.min.js'.
	anHtmlRoot javascript defer; url: '/lib/uikit-3/js/uikit-icons.min.js'.

	anHtmlRoot stylesheet url: '/js/jquery.webui-popover.min.css'.
	anHtmlRoot javascript defer; url: '/js/jquery.webui-popover.min.js'.

	"Print helper"
	anHtmlRoot javascript defer; url: '/js/printThis/printThis.js'.
