as yet unclassified
updateRootStandardJsUiLibs: anHtmlRoot

	"Mouse/Touch events unifier for dragging, ..."
	"TODO: Maybe only as feature request in a module exerciser?"
	"Previous used version: 1.10.11"
"	anHtmlRoot javascript defer; url: 'https://cdn.jsdelivr.net/npm/interactjs@1.10.26/dist/interact.min.js'."
	anHtmlRoot javascript defer; url: '/js/interact.min.js'. "Version 1.10.27"

	"List drag/drop sorting library"
	"TODO: Maybe only as feature request in a module exerciser?"
"stupid hsts cert problems	anHtmlRoot javascript defer; url: 'https://cdn.jsdelivr.net/npm/sortablejs@latest/Sortable.min.js'."
	anHtmlRoot javascript defer; url: '/js/Sortable.min.js'. "Version 1.15.2"

	"Textareas autosizing"
	anHtmlRoot javascript defer; url: '/js/jquery.autosize.js'.

