SystemOrganization addCategory: #'Pillar-ExporterCore'!
SystemOrganization addCategory: #'Pillar-ExporterCore-Base'!
SystemOrganization addCategory: #'Pillar-ExporterCore-Configuration'!
SystemOrganization addCategory: #'Pillar-ExporterCore-Exceptions'!
SystemOrganization addCategory: #'Pillar-ExporterCore-Numbering'!
SystemOrganization addCategory: #'Pillar-ExporterCore-Utilities'!
SystemOrganization addCategory: #'Pillar-ExporterCore-Visitor'!
